apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
data:
  index.html: |
    <html>
    <h1>Welcome DJ!</h1>
    </br>
    <h1>I got deployed in {{ .Values.env.name }} Environment using Helm Chart </h1>
    </html