replicaCount: 1

image:
  repository: nginx
  tag: "1.16.0"
  pullPolicy: IfNotPresent

service:
  name: nginx-service
  type: NodePort
  nodePort: 3007
  port: 80
  targetPort: 9000

namespace: helm-demo

env:
  name: dev
